% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Final Project - Draft Analysis},
  pdfauthor={Blanka Balazs, Simon Fernezelyi, Thea Goslicki},
  colorlinks=true,
  linkcolor={Maroon},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={blue},
  pdfcreator={LaTeX via pandoc}}

\title{Final Project - Draft Analysis}
\author{Blanka Balazs, Simon Fernezelyi, Thea Goslicki}
\date{}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}
\textbf{\#\#Research question:} To what extent had the implementation of Fox News an effect on the US voting behavior during the presidential elections 1996 \& 2000?

\hypertarget{introduction}{%
\section{\texorpdfstring{\textbf{Introduction}}{Introduction}}\label{introduction}}

\hypertarget{literature-review}{%
\section{Literature Review}\label{literature-review}}

In recent decades, there has been increasing attention on the role of media during political campaigns and its effects on the actual outcomes of elections. However, it is still debated within academia to what extent news media influence the behavior of the electorate. A potential answer to the question is that news media does not have an actual effect on people's voting behavior. It is called the sociological model of voting behavior which states that people's voting behavior is determined by long-term factors. This theory is supported by Lazarsfeld, Berelson, and Gaudet's (Lazarsfeld, Berelson, and Gaudet 1968) research analysis whose results show that the effect of media on electoral decisions is minimal but people belonging to different social groups is what determines their voting behavior. Kriesi, Grande, and Lachat (Kriesi et al. 2008) also argue people's voting behavior is determined by their belonging to different cleavages. However, instead of the old cleavages, there is a new social division within society that defines people's voting behavior which is the distinction between the winners and losers of globalization (Kriesi et al. 2008). Losers of globalization feel that their social status is protected by the nation-state and therefore they are strongly connected and identify themselves with the national community and that is what determines their voting behavior (Kriesi et al. 2008). In contrast, the winners of globalization benefit from open borders, they have more opportunities and therefore they vote differently (Kriesi et al. 2008) (I wrote this down because maybe we could test if there is any relationship between the number of Fox news subscribers in states that are doing worse economically and those that have developed in the last few decades)

However, other authors argue that issue voting explains voters' party choice which is based on voters' preferences on salient political issues. This theory argues that short-term factors like media attention, campaigns, and current determinant issues in politics determine people's voting behavior. This theory is supported by DeMarzo, Vayanos, and Zwiebel's (DeMarzo, Vayanos, and Zwiebel 2003) research analysis that persuasion bias (like propaganda, censorship, political spin, and marketing) plays an important role in the process of social opinion formation and as a consequence, it determines people's voting behavior.

\hypertarget{hypotheses}{%
\section{Hypotheses}\label{hypotheses}}

This paper will follow Lazarsfeld et al.'s (1944) approach and main Hypotheses: The act of voting is an individual act, affected mainly by the personality of the voter and his exposure to the media.In the case of our research and our available data, we categorize the variables about socioeconomic background of the people as personality trades and the exposure to media via the existence or non-existence of Fox News.

\textbf{HP1:} Fox news and the socioeconomic background affects the behavior of the electorate.

Sociological model of voting Kriesi's (Kriesi et al. 2008): People's voting behavior is just shaped by long-term factors (socialization).

\textbf{HP2:} Just socioeconomic background affects the behavior of the electorate.

Rational expectation theories (Bray and Kreps 1987) :Voters often filter out reporting bias without being influenced. The implementation of Fox News will not effect election results.

\hypertarget{loading-data-general-overview-over-the-data}{%
\section{Loading Data \& General Overview over the data}\label{loading-data-general-overview-over-the-data}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"foxnews.csv"}\NormalTok{)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{state }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{state)}
\end{Highlighting}
\end{Shaded}

In order to have a rough overview of the vote share among states, the \emph{state} variable is converted into a factor variable. Afterwards the average two-party vote share for the Republicans at 2000 Presidential election in the different states is shown in this table in increasing order.

\begin{verbatim}
##        Ri        Hi        Ma        Ct        Ca        Nj        Vt        Ar 
## 0.3782243 0.3866320 0.3949739 0.4390149 0.4471664 0.4674222 0.4708586 0.4947215 
##        Me        Tn        Ia        Wi        Nh        Mn        Sc        Ny 
## 0.5017892 0.5105959 0.5268057 0.5291817 0.5294599 0.5317263 0.5318809 0.5400148 
##        Mi        Al        Va        Pa        Mo        Oh        Ak        Nd 
## 0.5464333 0.5633230 0.5649642 0.5663298 0.5778050 0.5817919 0.6168280 0.6742668 
##        Mt        Id        Wy        Ut 
## 0.6749542 0.7337415 0.7495900 0.7981762
\end{verbatim}

From these values it is already obvious that there is quite a big variation between the two-party vote share for the Republicans in different states (highest and lowest being Utah (0.7981762) and Rhode Island (0.3782243) respectively).

Afterwards the two-party vote share is calculated for the other two measurement time points as well and the trends are illustrated on a plot below.

\includegraphics{final_project_files/figure-latex/unnamed-chunk-3-1.pdf}

Obviously this graph is not intended to clearly show the variance of each state, rather the general trends in the different states over time. From this plot it is clear that on average there has been a slight decrease in republican vote share in the period of 1992 and 1996, however there has been differences in different region. For example Main experienced a huge drop while in Idaho a slight increase is visible.

On the other hand in the time period of 1996 and 2000 there has been a strong increase (on average from 0.468436 to 0.5474526 ). An important note is that there has been no single state where the republican vote share has decreased in this time period.

Introducing the correlation analysis

\begin{verbatim}
##                  college1990    male1990   black1990    hisp1990  income1990
## college1990       1.00000000 -0.02564961 -0.04951600  0.01102930  0.67344439
## male1990         -0.02564961  1.00000000 -0.08323473  0.10585356  0.15350228
## black1990        -0.04951600 -0.08323473  1.00000000  0.06078667 -0.13253234
## hisp1990          0.01102930  0.10585356  0.06078667  1.00000000  0.01149702
## income1990        0.67344439  0.15350228 -0.13253234  0.01149702  1.00000000
## gopvoteshare2000 -0.09908543  0.18130369 -0.33131949 -0.22898806  0.01933208
##                  gopvoteshare2000
## college1990           -0.09908543
## male1990               0.18130369
## black1990             -0.33131949
## hisp1990              -0.22898806
## income1990             0.01933208
## gopvoteshare2000       1.00000000
\end{verbatim}

Interpreting the correlation results

\includegraphics{final_project_files/figure-latex/unnamed-chunk-5-1.pdf}
This scatter plot gives an first overview between the share of Fox News subscribers by town and the share for republicans in the presidential election in 2000.Three fundamental things, which are a basis for further analysis, can be read from the scatterplot: (1) no clear direction of the data is discernible at first glance; (2) cities that did not have access to Fox News in 2000 range across the spectrum of Republican support, from no Fox News and low support for Republicans to no Fox News and very high vote share for Republicans. (3) it looks like (purely visual `first analysis') the majority of cities are around the cut point (0.5/0.4), which means there are a lot of cities that are relatively split between Democrats and Republicans and between having or not having Fox News. Since most of the data is expressed in proportions, this also means that there will be many values in the middle.
\includegraphics{final_project_files/figure-latex/unnamed-chunk-6-1.pdf}

To get a better picture of the implementation of Fox News in the USA, the share of Fox News subscribers by state in 2000 got plotted. The differences are immense. New Hampshire does not have any access to Fox News in 2000 yet, also in Vermont, Massachusetts and South Carolina is the access ratio to the Fox News Channel almost non existence. On the other hand is the channel already very accessible in states like New Jersey,Wyoming and Alaska. According to the bar plot has the biggest proportion of Fox News subscribers. However, due to the fact, that the bar plot does not represents the number of Fox News subscribers, only the the proportion of citizens with a subscription per town it does not mean that Hawii does have the highest amount in a quantitative sense.

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##  0.0000  0.0000  0.0000  0.0672  0.0000  1.0000     331
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##        0.5553654        0.4979565        0.5483298
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##        0.5009744        0.4784179        0.5369426
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##        0.4797481        0.4679651        0.5392109
\end{verbatim}

\includegraphics{final_project_files/figure-latex/unnamed-chunk-7-1.pdf}

To Test the hypotheses of the research and to measure the effect of the treatment, it is crucial to define the independent variable of the paper: the access to Fox News by the year 2000.As mentioned above Fox News got implemented in 1996. Therefore, the cities without any access to Fox News in 2000 got characterized as `Towns without Fox News'. Cities who have a share of Fox News subscribers over 0.75 got defines as `Towns with Fox News', due to the fact, that 75\% of the inhabitants is a clear majority, especially when we consider that people live in households with other persons. The data set does not elaborate the information whether children or other people who are not allowed to vote in the states ( like prisoners) are included or not,however a threshold of 0.75 this circumstance cushions instead a threshold of 1. The third subset will be `Towns with some Fox News', in particular all towns between the 0 and 0.75 will be part of it.

The graph illustrates that in all cities, no matter how much access to Fox News the various cities had, there was an increase in Republican voters in 2000, compared to the 1996 presidential election. Nevertheless, a staggered effect of the different groups can be seen, even if it is small.Cities with Fox News voted for the Republican president by a larger percentage in both 1996 (the year Fox News was implemented in some cities) and the 2000 presidential election. Cities without any Fox News access were the least likely to vote in favor of Republicans, even though the percentage of Republican voters nevertheless increased in 2000.

\hypertarget{sample-average-treatment-effect-fox-news-effect-among-socioeconomic-variables}{%
\section{Sample average treatment effect (`Fox News Effect') among socioeconomic variables}\label{sample-average-treatment-effect-fox-news-effect-among-socioeconomic-variables}}

Our hypotheses stating, that it might be possible that socioeconomic backgrouds like education and race of people influence a potential `Fox News Effect' differently . It could be also possible that voters with different incomes get effected differently by the input of Fox News.

We will evaluate whether these hypotheses are supported by finding the differences in sample average treatment effects by education, race and income in towns with access to Fox News and towns without access to Fox News.

Furthermore,the average change of votes for republican (during presidential elections) among towns before and after the availability of Fox News could be an crucial indicator to understand the effect, therefore it wil be computed.

\#SATE among race (black)

\begin{verbatim}
##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## 0.000000 0.000000 0.002165 0.031380 0.013411 0.990427
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##       0.10925987       0.05064534       0.12910528
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##      0.093132523      0.020481978      0.001447365
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##       0.08757249       0.07211261       0.05586653
\end{verbatim}

\includegraphics{final_project_files/figure-latex/unnamed-chunk-8-1.pdf}
\textless\textless\textless\textless\textless\textless\textless{} HEAD
The first thing we looked at was whether the introduction of Fox News had a bigger/smaller impact on black people in the USA. The cities were divided into subsets, to take into account different proportions of black people in the cities. For the subdivision of cities and their black population, the different quantiles were not looked at, which is the case in the following SATE calculations. Due to the white majority population in the states, the third quantile of the proportion of black people would have been 0.013411 but the maximum would have been 0.990427. The difference between 1\% and 99\% would have been too serious to categorize all cities in between as having a high black population. That's why cities with a percentage above 0.40 were considered to have a high black population. As can be seen in the plot, only the line from the cities with a high black population share has a similar shape to the lines in the plot with the general trend effect. In the cities with a low proportion or none at all, the estimated treatment effect goes in a negative direction.

\hypertarget{sate-among-race-hispanic}{%
\section{\#SATE among race (hispanic)}\label{sate-among-race-hispanic}}

The first thing we looked at was whether the introduction of Fox News had a bigger/smaller impact on black people in the USA. The cities were divided into subsets, to take into account different proportions of black people in the cities. For the subdivision of cities and their black population, the different quantiles were not looked at, which is the case in the following SATE calculations. Due to the white majority population in the states, the third quantile of the proportion of black people would have been 0.013411 but the maximum would have been 0.990427. The difference between 1\% and 99\% would have been too serious to categorize all cities in between as having a high black population. That's why cities with a percentage above 0.40 were considered to have a high black population. As can be seen in the plot, only the line from the cities with a high black population share has a similar shape to the lines in the plot with the general trend effect. In the cities with a low proportion or none at all, the estimated treatment effect goes in a negative direction.

\begin{quote}
\begin{quote}
\begin{quote}
\begin{quote}
\begin{quote}
\begin{quote}
\begin{quote}
2b728532b740c24e648b533972c4c6903c469f54
\end{quote}
\end{quote}
\end{quote}
\end{quote}
\end{quote}
\end{quote}
\end{quote}

\begin{verbatim}
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## 0.0000000 0.0009644 0.0054680 0.0197700 0.0137693 0.8616408
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##              NaN              NaN              NaN
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##      0.095510779      0.033633718      0.009345288
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##      0.013692200      0.011972294      0.005674159
\end{verbatim}

\includegraphics{final_project_files/figure-latex/unnamed-chunk-9-1.pdf}
\#SATE among income

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{income1990)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.420   1.946   2.586   2.808   3.420  15.000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#SATE town with high proportion of rich people}

\NormalTok{high\_income.t\_w\_foxnews}\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(towns\_w\_foxnews, }\AttributeTok{subset =}\NormalTok{ income1990 }\SpecialCharTok{\textgreater{}=} \FloatTok{3.420}\NormalTok{)}
\NormalTok{high\_income.t\_no\_foxnews}\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(towns\_no\_foxnews, }\AttributeTok{subset =}\NormalTok{ income1990 }\SpecialCharTok{\textgreater{}=} \FloatTok{3.420}\NormalTok{)}

\NormalTok{means\_high\_income.t\_w\_foxnews}\OtherTok{\textless{}{-}}\FunctionTok{colMeans}\NormalTok{(high\_income.t\_w\_foxnews[}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}gopvoteshare1992\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare1996\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare2000\textquotesingle{}}\NormalTok{)], }\AttributeTok{na.rm =}\NormalTok{ T)}

\NormalTok{means\_high\_income.t\_no\_foxnews}\OtherTok{\textless{}{-}}\FunctionTok{colMeans}\NormalTok{(high\_income.t\_no\_foxnews[}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}gopvoteshare1992\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare1996\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare2000\textquotesingle{}}\NormalTok{)], }\AttributeTok{na.rm =}\NormalTok{ T)}

\NormalTok{sate\_high\_income.t\_w\_foxnews}\OtherTok{\textless{}{-}}\NormalTok{means\_high\_income.t\_w\_foxnews}\SpecialCharTok{{-}}\NormalTok{ means\_high\_income.t\_no\_foxnews}
\NormalTok{sate\_high\_income.t\_w\_foxnews}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##        0.1003546        0.1063854        0.1154779
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#SATE town with medium income}

\NormalTok{medium\_income.t\_w\_foxnews}\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(towns\_w\_foxnews, }\AttributeTok{subset =}\NormalTok{ income1990 }\SpecialCharTok{\textgreater{}}\FloatTok{1.946} \SpecialCharTok{\&}\NormalTok{ income1990 }\SpecialCharTok{\textless{}}\FloatTok{3.420}\NormalTok{ )}
\NormalTok{medium\_income.t\_no\_foxnews}\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(towns\_no\_foxnews, }\AttributeTok{subset =}\NormalTok{income1990 }\SpecialCharTok{\textgreater{}}\FloatTok{1.946} \SpecialCharTok{\&}\NormalTok{ income1990 }\SpecialCharTok{\textless{}}\FloatTok{3.420}\NormalTok{ )}

\NormalTok{means\_medium\_income.t\_w\_foxnews}\OtherTok{\textless{}{-}}\FunctionTok{colMeans}\NormalTok{(medium\_income.t\_w\_foxnews[}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}gopvoteshare1992\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare1996\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare2000\textquotesingle{}}\NormalTok{)], }\AttributeTok{na.rm =}\NormalTok{ T)}

\NormalTok{means\_medium\_income.t\_no\_foxnews}\OtherTok{\textless{}{-}}\FunctionTok{colMeans}\NormalTok{(medium\_income.t\_no\_foxnews[}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}gopvoteshare1992\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare1996\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare2000\textquotesingle{}}\NormalTok{)], }\AttributeTok{na.rm =}\NormalTok{ T)}


\NormalTok{sate\_medium\_income.t\_w\_foxnews}\OtherTok{\textless{}{-}}\NormalTok{means\_medium\_income.t\_w\_foxnews }\SpecialCharTok{{-}}\NormalTok{ means\_medium\_income.t\_no\_foxnews}
\NormalTok{sate\_medium\_income.t\_w\_foxnews}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##      0.125518279      0.002530465     -0.023026159
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#SATE town with high proportion of poor people}

\NormalTok{low\_income.t\_w\_foxnews}\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(towns\_w\_foxnews, }\AttributeTok{subset =}\NormalTok{ income1990 }\SpecialCharTok{\textless{}=} \FloatTok{1.946}\NormalTok{)}
\NormalTok{low\_income.t\_no\_foxnews}\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(towns\_no\_foxnews, }\AttributeTok{subset =}\NormalTok{ income1990 }\SpecialCharTok{\textless{}=} \FloatTok{1.946}\NormalTok{)}


\NormalTok{means\_low\_income.t\_w\_foxnews}\OtherTok{\textless{}{-}}\FunctionTok{colMeans}\NormalTok{(low\_income.t\_w\_foxnews[}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}gopvoteshare1992\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare1996\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare2000\textquotesingle{}}\NormalTok{)], }\AttributeTok{na.rm =}\NormalTok{ T)}

\NormalTok{means\_low\_income.t\_no\_foxnews}\OtherTok{\textless{}{-}}\FunctionTok{colMeans}\NormalTok{(low\_income.t\_no\_foxnews[}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}gopvoteshare1992\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare1996\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}gopvoteshare2000\textquotesingle{}}\NormalTok{)], }\AttributeTok{na.rm =}\NormalTok{ T)}


\NormalTok{sate\_low\_income.t\_w\_foxnews}\OtherTok{\textless{}{-}}\NormalTok{ means\_low\_income.t\_w\_foxnews}\SpecialCharTok{{-}}\NormalTok{ means\_low\_income.t\_no\_foxnews}
\NormalTok{sate\_high\_income.t\_w\_foxnews}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##        0.1003546        0.1063854        0.1154779
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(years,sate\_high\_income.t\_w\_foxnews, }\AttributeTok{pch =} \DecValTok{16}\NormalTok{, }\AttributeTok{col =} \StringTok{"green"}\NormalTok{,}
\AttributeTok{xlim =} \FunctionTok{c}\NormalTok{(}\DecValTok{1992}\NormalTok{, }\DecValTok{2000}\NormalTok{), }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{0.2}\NormalTok{, }\FloatTok{0.2}\NormalTok{), }\AttributeTok{xlab =} \StringTok{"Years of presidential election"}\NormalTok{,}
\AttributeTok{ylab =} \StringTok{"Estimated sample average fox news effect"}\NormalTok{,}
\AttributeTok{main =} \StringTok{"Trends in Fox News Effects among income"}\NormalTok{)}

\FunctionTok{points}\NormalTok{(years, sate\_medium\_income.t\_w\_foxnews,}\AttributeTok{pch =} \DecValTok{16}\NormalTok{, }\AttributeTok{col =} \StringTok{"orange"}\NormalTok{)}
\FunctionTok{points}\NormalTok{(years, sate\_low\_income.t\_w\_foxnews,}\AttributeTok{pch =} \DecValTok{16}\NormalTok{, }\AttributeTok{col =} \StringTok{"brown"}\NormalTok{)}


\FunctionTok{lines}\NormalTok{(years,sate\_high\_income.t\_w\_foxnews, }\AttributeTok{type=}\StringTok{"c"}\NormalTok{, }\AttributeTok{col=}\StringTok{"green"}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(years, sate\_medium\_income.t\_w\_foxnews,}\AttributeTok{type=}\StringTok{"c"}\NormalTok{, }\AttributeTok{col =} \StringTok{"orange"}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(years, sate\_low\_income.t\_w\_foxnews,}\AttributeTok{type=}\StringTok{"c"}\NormalTok{, }\AttributeTok{col =} \StringTok{"brown"}\NormalTok{)}

\FunctionTok{text}\NormalTok{(}\DecValTok{1993}\NormalTok{,}\FloatTok{0.13}\NormalTok{,}\StringTok{"High income"}\NormalTok{, }\AttributeTok{col=}\StringTok{"green"}\NormalTok{)}
\FunctionTok{text}\NormalTok{(}\DecValTok{1998}\NormalTok{,}\SpecialCharTok{{-}}\FloatTok{0.06}\NormalTok{,}\StringTok{"Medium income"}\NormalTok{, }\AttributeTok{col=}\StringTok{"orange"}\NormalTok{)}
\FunctionTok{text}\NormalTok{(}\DecValTok{1998}\NormalTok{, }\FloatTok{0.02}\NormalTok{, }\StringTok{"Low income"}\NormalTok{, }\AttributeTok{col=}\StringTok{"brown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_files/figure-latex/unnamed-chunk-10-1.pdf}
Looking at income and the potential sample average treatment effect we can see, that only for persons with high income (towns where the average income is over or equals 3.420\$) the estimated sample average Fox News effect is increasing and more rich people voted for republicans but an the other hand the vote share for Republicans among rich people normally quite high anyways. Therefore it is hard to argue, that the implementation of Fox News is the main reason. Towns with a medium income or low income have decresing sampel average treatment effect.

\#SATE among level of education

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00000 0.08145 0.12257 0.15582 0.19255 0.78536
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##       -0.1003546       -0.1063854       -0.1154779
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##      0.101808195      0.026188799      0.003435166
\end{verbatim}

\begin{verbatim}
## gopvoteshare1992 gopvoteshare1996 gopvoteshare2000 
##       -0.1003546       -0.1063854       -0.1154779
\end{verbatim}

\includegraphics{final_project_files/figure-latex/unnamed-chunk-11-1.pdf}
The last measurement of finding the differences in sample average treatment effects by socioeconomic backgrounds is SATE for diffrent levels of education. Here is it visible, that high educated regions are less likely to vote for republicans and have lower starting position. Looking at a medium or low level of education a possible \ldots\ldots.

\hypertarget{regression-analysis}{%
\section{Regression analysis}\label{regression-analysis}}

We will test H1 (Fox news and the socioeconomic background affects the behavior of the electorate) and H2 (just socioeconomic background affects the behavior of the electorate) through regression analysis. First, we will test to what extent socioeconomic factors affect people's vote for the Republican party. We included in the analysis the proportion of inhabitants who have a college degree, the median income, and the proportion of black or Hispanic people in every city. Black and Hispanic people stand for minorities in the analysis because these are the two most significant minorities and only these two minorities were included in the data set.

\begin{verbatim}
## 
## Call:
## lm(formula = gopvoteshare2000 ~ income1990 + hisp_or_black + 
##     college1990, data = data)
## 
## Coefficients:
##   (Intercept)     income1990  hisp_or_black    college1990  
##        0.5659         0.0101        -0.4418        -0.2063
\end{verbatim}

\begin{verbatim}
## [1] 0.1714018
\end{verbatim}

The results of the analysis show that in cities where the proportion of minorities (Hispanic and Black people) is higher the support for the Republican party is lower than in other cities. Therefore, from the socioeconomic factors that were included in the regression analysis race (-0.4418) has the strongest effect on support for the Republican party in American cities. The proportion of people who have a college degree is also an important explanatory factor to explain vote for the Republican party in a city. In cities where the proportion of those who have a college degree is higher citizens -0.20627 are less likely to vote for the Republican party. Moreover, the median income in cities does not seem to have an effect on support for the Republican party.

In the following, we will test the influence of Fox News subscribers (in cities) on people's support for the Republican party. Furthermore, the proportion of Fox News subscribers will be added to the socio-economic factors to check what explains better people's vote for the Republican party.

\begin{verbatim}
## 
## Call:
## lm(formula = gopvoteshare2000 ~ subrf2000, data = data)
## 
## Coefficients:
## (Intercept)    subrf2000  
##     0.54012     -0.01888
\end{verbatim}

\begin{verbatim}
## [1] 0.0004145752
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = gopvoteshare2000 ~ income1990 + hisp_or_black + 
##     college1990 + subrf2000, data = data)
## 
## Coefficients:
##   (Intercept)     income1990  hisp_or_black    college1990      subrf2000  
##      0.567277       0.009573      -0.440242      -0.206280      -0.008145
\end{verbatim}

\begin{verbatim}
## [1] 0.171275
\end{verbatim}

The analysis shows that there is no real correlation (-0.019) between Fox News subscribers and the support for the Republican party. Therefore, the proportion of Fox News subscribers does not explain citizens' support for the Republican party. Furthermore, when the proportion of Fox News subscribers was added to the regression the influence of Fox News subscribers on people's support for the republican party became even weaker which means that socioeconomic factors better explain their support for the Republican party than Fox News subscribers.

However, the results can be misleading because there are much more towns in the data set where there is no access to Fox News or it is very limited. The over representation of these cities can have an effect on the results. Therefore, we created two sub groups. The first group includes cities where more than half of the inhabitants have access to Fox News and the second group includes those towns where less than the half of the population have access to Fox news.

\begin{verbatim}
## 
## Call:
## lm(formula = gopvoteshare2000 ~ subrf2000, data = foxnews_present)
## 
## Coefficients:
## (Intercept)    subrf2000  
##     0.49679      0.03746
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = gopvoteshare2000 ~ subrf2000, data = foxnews_not_present)
## 
## Coefficients:
## (Intercept)    subrf2000  
##      0.5402      -0.0186
\end{verbatim}

The regression analysis shows that the effect of access to Fox News is still very marginal 0.037. In cities where more than half of the population have access to Fox News people are more likely to support the republican party compare to those towns where less than half of the population have access to Fox News.

\hypertarget{prediction}{%
\section{Prediction}\label{prediction}}

\includegraphics{final_project_files/figure-latex/unnamed-chunk-15-1.pdf}

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

\newpage

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-Bray1987}{}}%
Bray, Margaret, and David M. Kreps. 1987. {``Rational Learning and Rational Expectations.''} In \emph{Arrow and the Ascent of Modern Economic Theory}, 597--625. Palgrave Macmillan {UK}. \url{https://doi.org/10.1007/978-1-349-07239-2_19}.

\leavevmode\vadjust pre{\hypertarget{ref-DeMarzo2003}{}}%
DeMarzo, P. M., D. Vayanos, and J. Zwiebel. 2003. {``Persuasion Bias, Social Influence, and Unidimensional Opinions.''} \emph{The Quarterly Journal of Economics} 118 (3): 909--68. \url{https://doi.org/10.1162/00335530360698469}.

\leavevmode\vadjust pre{\hypertarget{ref-Kriesi2008}{}}%
Kriesi, Hanspeter, Edgar Grande, Romain Lachat, Martin Dolezal, Simon Bornschier, and Timotheos Frey. 2008. \emph{West European Politics in the Age of Globalization}. Cambridge University Press. \url{https://doi.org/10.1017/cbo9780511790720}.

\leavevmode\vadjust pre{\hypertarget{ref-Lazarsfeld1968}{}}%
Lazarsfeld, Paul F., Bernard Berelson, and Hazel Gaudet. 1968. \emph{The People's Choice}. Columbia University Press. \url{https://doi.org/10.7312/laza93930}.

\end{CSLReferences}

\end{document}
